name: Build and Push Image to ECR Registry

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Optional for tagging a immutable version (e.g., 0.1.1)'
        type: string
        required: false
      region:
        description: 'AWS Region'
        type: string
        required: true
        default: us-east-1

permissions:
  id-token: write
  contents: write  # Added for Git tagging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.SAAS_AWS_DEPLOY_ROLE_ARN }}
          role-session-name: ecr-build-session

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "897729109735"

      - name: Set image tags
        id: set-tags
        run: |
          ECR_REGISTRY="897729109735.dkr.ecr.${{ inputs.region }}.amazonaws.com"
          ECR_REPOSITORY="jarvis/zendesk_mcp_server"
          TAGS="$ECR_REGISTRY/$ECR_REPOSITORY:latest
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
          if [ -n "${{ inputs.release_version }}" ]; then
            TAGS="$TAGS
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.release_version }}"
          fi
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}

      - name: Summary
        run: |
          echo "## 🚀 Build and Push Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit SHA:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker tags pushed:**" >> $GITHUB_STEP_SUMMARY
          echo "  - \`latest\`" >> $GITHUB_STEP_SUMMARY
          echo "  - \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ inputs.release_version }}" ]; then
            echo "  - \`${{ inputs.release_version }}\`" >> $GITHUB_STEP_SUMMARY
          fi